### ISSUE TITLE
ubuntu 12.04 TypeError: parse_requirements() got an unexpected keyword argument 'session'

### ISSUE THREAD

**Issue by Exocomp** [arachnys/cabot#437]
I installed Cabot on a stock ubuntu 12.04 LTS however, I'm getting the following error when I deploy:

`[ubuntu@alert] sudo: foreman run -e conf/production.env /home/ubuntu/venv/bin/pip install --editable /home/ubuntu/2017-02-23-206abcd --exists-action=w
[ubuntu@alert] out: Obtaining file:///home/ubuntu/2017-02-23-206abcd
[ubuntu@alert] out:   Running setup.py egg_info for package from file:///home/ubuntu/2017-02-23-206abcd
[ubuntu@alert] out:     Traceback (most recent call last):
[ubuntu@alert] out:       File "<string>", line 14, in <module>
[ubuntu@alert] out:       File "/home/ubuntu/2017-02-23-206abcd/setup.py", line 9, in <module>
[ubuntu@alert] out:         requirements = [str(req.req) for req in parse_requirements('requirements.txt', session=False)]
[ubuntu@alert] out:     TypeError: parse_requirements() got an unexpected keyword argument 'session'
[ubuntu@alert] out:     Complete output from command python setup.py egg_info:
[ubuntu@alert] out:     Traceback (most recent call last):
[ubuntu@alert] out:
[ubuntu@alert] out:   File "<string>", line 14, in <module>
[ubuntu@alert] out:
[ubuntu@alert] out:   File "/home/ubuntu/2017-02-23-206abcd/setup.py", line 9, in <module>
[ubuntu@alert] out:
[ubuntu@alert] out:     requirements = [str(req.req) for req in parse_requirements('requirements.txt', session=False)]
[ubuntu@alert] out:
[ubuntu@alert] out: TypeError: parse_requirements() got an unexpected keyword argument 'session'
[ubuntu@alert] out:
[ubuntu@alert] out: ----------------------------------------
[ubuntu@alert] out: Command python setup.py egg_info failed with error code 1 in /home/ubuntu/2017-02-23-206abcd
[ubuntu@alert] out: Storing complete log in /home/ubuntu/.pip/pip.log
[ubuntu@alert] out:

Fatal error: sudo() received nonzero return code 1 while executing!
`

From researching this erorr "**TypeError: parse_requirements() got an unexpected keyword argument 'session'**", it appears the wrong version of python/pip was installed.

I have:

administrator@alert:~/cabot$ pip -V
**pip 9.0.1** from /usr/local/lib/python2.7/dist-packages (python 2.7)
administrator@alert:~/cabot$ python -V
**Python 2.7.3**

Can you please review and let me know how to proceed.

Thanks,
E

**Comment by JeanFred** [comment]
@Exocomp What was the issue in the end ? :)

**Comment by Exocomp** [comment]
Appears it is a versioning issue, I got it to work on ubuntu 14.04 instead, so not really worth it to fix it on stock 12.04.
